export const invitationCopy = {
  en: {
    involved: "Get involved", title: "Let's build something together.", intro: "Three ways to work with Ravolution. Tell us which fits — Ivan reviews every message personally.", tabs: ["Invest", "Partner", "Other"],
    invest: "Back one or more of our platforms, as an angel or a strategic partner. Explore systems spanning language, health, climate, trust and education. Tick the ones you'd like to explore and we'll open a direct, private conversation about stage, terms and ticket size.",
    partner: "Have strong tech but gaps around it? Tell us what you're building and what you need — we contribute build, brand, IP and go-to-market, and we invest.", other: "Something else in mind — a collaboration, a press or speaking request, an idea? Tell us.", looking: "What you're looking for", message: "Your message", startup: "Describe your startup", deck: "Pitch deck URL (optional)", name: "Name", company: "Company", email: "Email", consent: "I agree that Ravolution may store my details and reply to me. See the", privacy: "privacy policy", send: "Send", sending: "Sending…", foot: "A private conversation. No spam, ever.", done: "Your message is on its way.", thanks: "Thanks — Ivan reviews every message personally. Expect a reply shortly.", copy: "We've also emailed you a copy of your message.", close: "Close", error: "Your message could not be sent. Please try again.", invalid: "Check your name, email, privacy consent and any pitch deck link.",
    descriptions: ["Learn language via music on Spotify", "Voice anti-deepfake", "Fully transparent recruitment platform", "Community OS", "Carbon trading platform", "Ingredient transparency", "Eye-health intelligence", "Global digital education", "Export infrastructure", "AI eldercare companion", "Contracts & e-sign", "EU AI Act compliance", "Ravolution AB itself", "Recommend one"], companyChoice: "The invention company", unsure: "Not sure yet",
  },
  sv: {
    involved: "Engagera dig", title: "Låt oss bygga något tillsammans.", intro: "Tre sätt att arbeta med Ravolution. Berätta vad som passar — Ivan läser varje meddelande personligen.", tabs: ["Investera", "Partner", "Annat"],
    invest: "Stötta en eller flera av våra plattformar som affärsängel eller strategisk partner. Utforska system inom språk, hälsa, klimat, tillit och utbildning. Markera de som intresserar dig så inleder vi ett direkt, privat samtal om fas, villkor och investeringsstorlek.",
    partner: "Har ni stark teknik men behöver stöd runt den? Berätta vad ni bygger och behöver — vi bidrar med utveckling, varumärke, IP och marknadsintroduktion, och vi investerar.", other: "Något annat i åtanke — samarbete, press, föreläsning eller en idé? Berätta.", looking: "Vad ni söker", message: "Ditt meddelande", startup: "Beskriv ert företag", deck: "Länk till presentation (valfritt)", name: "Namn", company: "Företag", email: "E-post", consent: "Jag godkänner att Ravolution sparar mina uppgifter och svarar mig. Se vår", privacy: "integritetspolicy", send: "Skicka", sending: "Skickar…", foot: "Ett privat samtal. Ingen skräppost, någonsin.", done: "Ditt meddelande är på väg.", thanks: "Tack — Ivan läser varje meddelande personligen. Du får svar inom kort.", copy: "Vi har även mejlat dig en kopia av ditt meddelande.", close: "Stäng", error: "Meddelandet kunde inte skickas. Försök igen.", invalid: "Kontrollera namn, e-post, samtycke och eventuell presentationslänk.",
    descriptions: ["Lär dig språk via musik på Spotify", "Skydd mot röst-deepfakes", "Transparent rekryteringsplattform", "Operativsystem för gemenskaper", "Plattform för kolhandel", "Ingredienstransparens", "Kunskap om ögonhälsa", "Global digital utbildning", "Exportinfrastruktur", "AI-sällskap för äldre", "Avtal och e-signering", "Efterlevnad av EU:s AI-förordning", "Ravolution AB självt", "Rekommendera ett alternativ"], companyChoice: "Uppfinningsföretaget", unsure: "Inte säker än",
  },
  es: {
    involved: "Participa", title: "Construyamos algo juntos.", intro: "Tres maneras de colaborar con Ravolution. Cuéntanos cuál encaja — Ivan lee cada mensaje personalmente.", tabs: ["Invertir", "Colaborar", "Otros"],
    invest: "Apoya una o varias plataformas como inversor ángel o socio estratégico. Explora sistemas de idiomas, salud, clima, confianza y educación. Marca las que te interesan para abrir una conversación directa y privada sobre etapa, condiciones e inversión.",
    partner: "¿Tienes tecnología sólida pero necesitas apoyo? Cuéntanos qué construyes y qué necesitas — aportamos desarrollo, marca, propiedad intelectual y salida al mercado, e invertimos.", other: "¿Otra propuesta — colaboración, prensa, una charla o una idea? Cuéntanos.", looking: "Qué buscas", message: "Tu mensaje", startup: "Describe tu empresa", deck: "URL de presentación (opcional)", name: "Nombre", company: "Empresa", email: "Correo electrónico", consent: "Acepto que Ravolution guarde mis datos y me responda. Consulta la", privacy: "política de privacidad", send: "Enviar", sending: "Enviando…", foot: "Una conversación privada. Sin spam, nunca.", done: "Tu mensaje está en camino.", thanks: "Gracias — Ivan lee cada mensaje personalmente. Recibirás una respuesta pronto.", copy: "También hemos enviado una copia a tu correo.", close: "Cerrar", error: "No se pudo enviar. Inténtalo de nuevo.", invalid: "Revisa tu nombre, correo, consentimiento y enlace de presentación.",
    descriptions: ["Aprende idiomas con música en Spotify", "Protección contra deepfakes de voz", "Reclutamiento transparente", "Sistema para comunidades", "Comercio de carbono", "Transparencia de ingredientes", "Inteligencia sobre salud ocular", "Educación digital global", "Infraestructura de exportación", "Compañía con IA para mayores", "Contratos y firma electrónica", "Cumplimiento de la Ley de IA de la UE", "La propia Ravolution AB", "Recomienda una opción"], companyChoice: "La empresa de invención", unsure: "Aún no lo sé",
  },
};