/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmsoleRouteImport } from './routes/alarmsole'
import { Route as BeredskapadRouteImport } from './routes/beredskapad'
import { Route as EaktiebokDraknasteRouteImport } from './routes/eaktiebok-draknaste'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as HundelserRouteImport } from './routes/hundelser'
import { Route as MetadatamachineRouteImport } from './routes/metadatamachine'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartystaRouteImport } from './routes/partysta'
import { Route as PratisRouteImport } from './routes/pratis'
import { Route as StoryRouteImport } from './routes/story'
import { Route as StudioroomRouteImport } from './routes/studioroom'
import { Route as XportmatchRouteImport } from './routes/xportmatch'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangAlarmsoleRouteImport } from './routes/$lang/alarmsole'
import { Route as LangAngelInvestorRouteImport } from './routes/$lang/angel-investor'
import { Route as LangApplyRouteImport } from './routes/$lang/apply'
import { Route as LangApplyForInvestmentRouteImport } from './routes/$lang/apply-for-investment'
import { Route as LangBeredskapadRouteImport } from './routes/$lang/beredskapad'
import { Route as LangBlogRouteImport } from './routes/$lang/blog'
import { Route as LangBriefRouteImport } from './routes/$lang/brief'
import { Route as LangBuildForEquityRouteImport } from './routes/$lang/build-for-equity'
import { Route as LangConfigureRouteImport } from './routes/$lang/configure'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangEaktiebokDraknasteRouteImport } from './routes/$lang/eaktiebok-draknaste'
import { Route as LangEvidenceRouteImport } from './routes/$lang/evidence'
import { Route as LangHundelserRouteImport } from './routes/$lang/hundelser'
import { Route as LangInvestRouteImport } from './routes/$lang/invest'
import { Route as LangMetadatamachineRouteImport } from './routes/$lang/metadatamachine'
import { Route as LangPartnerRouteImport } from './routes/$lang/partner'
import { Route as LangPartystaRouteImport } from './routes/$lang/partysta'
import { Route as LangPatentStrategyForStartupsRouteImport } from './routes/$lang/patent-strategy-for-startups'
import { Route as LangPortfolioRouteImport } from './routes/$lang/portfolio'
import { Route as LangPratisRouteImport } from './routes/$lang/pratis'
import { Route as LangPrivacyPolicyRouteImport } from './routes/$lang/privacy-policy'
import { Route as LangSalesPartnerRouteImport } from './routes/$lang/sales-partner'
import { Route as LangServicesRouteImport } from './routes/$lang/services'
import { Route as LangStoryRouteImport } from './routes/$lang/story'
import { Route as LangStudioroomRouteImport } from './routes/$lang/studioroom'
import { Route as LangTechnicalCofounderAlternativeRouteImport } from './routes/$lang/technical-cofounder-alternative'
import { Route as LangTermsOfServiceRouteImport } from './routes/$lang/terms-of-service'
import { Route as LangXportmatchRouteImport } from './routes/$lang/xportmatch'
import { Route as BizmeetIndexRouteImport } from './routes/bizmeet/index'
import { Route as BizmeetDemoRouteImport } from './routes/bizmeet/demo'
import { Route as EsServiciosRouteImport } from './routes/es/servicios'
import { Route as EsSocioComercialRouteImport } from './routes/es/socio-comercial'
import { Route as PikpcashIndexRouteImport } from './routes/pikpcash/index'
import { Route as PikpcashDataroomRouteImport } from './routes/pikpcash/dataroom'
import { Route as PikpcashSystemRouteImport } from './routes/pikpcash/system'
import { Route as SvAnsokRouteImport } from './routes/sv/ansok'
import { Route as SvSaljpartnerRouteImport } from './routes/sv/saljpartner'
import { Route as SvTjansterRouteImport } from './routes/sv/tjanster'
import { Route as LangBizmeetIndexRouteImport } from './routes/$lang/bizmeet/index'
import { Route as LangBizmeetDemoRouteImport } from './routes/$lang/bizmeet/demo'
import { Route as LangGyrocraftIndexRouteImport } from './routes/$lang/gyrocraft/index'
import { Route as LangGyrocraftAboutRouteImport } from './routes/$lang/gyrocraft/about'
import { Route as LangGyrocraftAcquisitionRouteImport } from './routes/$lang/gyrocraft/acquisition'
import { Route as LangGyrocraftInvestorsRouteImport } from './routes/$lang/gyrocraft/investors'
import { Route as LangGyrocraftLicensingRouteImport } from './routes/$lang/gyrocraft/licensing'
import { Route as LangJournalIndexRouteImport } from './routes/$lang/journal/index'
import { Route as LangJournalSlugRouteImport } from './routes/$lang/journal/$slug'
import { Route as LangPikpcashIndexRouteImport } from './routes/$lang/pikpcash/index'
import { Route as LangPikpcashDataroomRouteImport } from './routes/$lang/pikpcash/dataroom'
import { Route as LangPikpcashSystemRouteImport } from './routes/$lang/pikpcash/system'
import { Route as LangVenturesPratisRouteImport } from './routes/$lang/ventures/pratis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsoleRoute = AlarmsoleRouteImport.update({
  id: '/alarmsole',
  path: '/alarmsole',
  getParentRoute: () => rootRouteImport,
} as any)
const BeredskapadRoute = BeredskapadRouteImport.update({
  id: '/beredskapad',
  path: '/beredskapad',
  getParentRoute: () => rootRouteImport,
} as any)
const EaktiebokDraknasteRoute = EaktiebokDraknasteRouteImport.update({
  id: '/eaktiebok-draknaste',
  path: '/eaktiebok-draknaste',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const HundelserRoute = HundelserRouteImport.update({
  id: '/hundelser',
  path: '/hundelser',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadatamachineRoute = MetadatamachineRouteImport.update({
  id: '/metadatamachine',
  path: '/metadatamachine',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartystaRoute = PartystaRouteImport.update({
  id: '/partysta',
  path: '/partysta',
  getParentRoute: () => rootRouteImport,
} as any)
const PratisRoute = PratisRouteImport.update({
  id: '/pratis',
  path: '/pratis',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioroomRoute = StudioroomRouteImport.update({
  id: '/studioroom',
  path: '/studioroom',
  getParentRoute: () => rootRouteImport,
} as any)
const XportmatchRoute = XportmatchRouteImport.update({
  id: '/xportmatch',
  path: '/xportmatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAlarmsoleRoute = LangAlarmsoleRouteImport.update({
  id: '/$lang/alarmsole',
  path: '/$lang/alarmsole',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAngelInvestorRoute = LangAngelInvestorRouteImport.update({
  id: '/$lang/angel-investor',
  path: '/$lang/angel-investor',
  getParentRoute: () => rootRouteImport,
} as any)
const LangApplyRoute = LangApplyRouteImport.update({
  id: '/$lang/apply',
  path: '/$lang/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LangApplyForInvestmentRoute = LangApplyForInvestmentRouteImport.update({
  id: '/$lang/apply-for-investment',
  path: '/$lang/apply-for-investment',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBeredskapadRoute = LangBeredskapadRouteImport.update({
  id: '/$lang/beredskapad',
  path: '/$lang/beredskapad',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBlogRoute = LangBlogRouteImport.update({
  id: '/$lang/blog',
  path: '/$lang/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBriefRoute = LangBriefRouteImport.update({
  id: '/$lang/brief',
  path: '/$lang/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBuildForEquityRoute = LangBuildForEquityRouteImport.update({
  id: '/$lang/build-for-equity',
  path: '/$lang/build-for-equity',
  getParentRoute: () => rootRouteImport,
} as any)
const LangConfigureRoute = LangConfigureRouteImport.update({
  id: '/$lang/configure',
  path: '/$lang/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/$lang/contact',
  path: '/$lang/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LangEaktiebokDraknasteRoute = LangEaktiebokDraknasteRouteImport.update({
  id: '/$lang/eaktiebok-draknaste',
  path: '/$lang/eaktiebok-draknaste',
  getParentRoute: () => rootRouteImport,
} as any)
const LangEvidenceRoute = LangEvidenceRouteImport.update({
  id: '/$lang/evidence',
  path: '/$lang/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const LangHundelserRoute = LangHundelserRouteImport.update({
  id: '/$lang/hundelser',
  path: '/$lang/hundelser',
  getParentRoute: () => rootRouteImport,
} as any)
const LangInvestRoute = LangInvestRouteImport.update({
  id: '/$lang/invest',
  path: '/$lang/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const LangMetadatamachineRoute = LangMetadatamachineRouteImport.update({
  id: '/$lang/metadatamachine',
  path: '/$lang/metadatamachine',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPartnerRoute = LangPartnerRouteImport.update({
  id: '/$lang/partner',
  path: '/$lang/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPartystaRoute = LangPartystaRouteImport.update({
  id: '/$lang/partysta',
  path: '/$lang/partysta',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPatentStrategyForStartupsRoute =
  LangPatentStrategyForStartupsRouteImport.update({
    id: '/$lang/patent-strategy-for-startups',
    path: '/$lang/patent-strategy-for-startups',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangPortfolioRoute = LangPortfolioRouteImport.update({
  id: '/$lang/portfolio',
  path: '/$lang/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPratisRoute = LangPratisRouteImport.update({
  id: '/$lang/pratis',
  path: '/$lang/pratis',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPrivacyPolicyRoute = LangPrivacyPolicyRouteImport.update({
  id: '/$lang/privacy-policy',
  path: '/$lang/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSalesPartnerRoute = LangSalesPartnerRouteImport.update({
  id: '/$lang/sales-partner',
  path: '/$lang/sales-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/$lang/services',
  path: '/$lang/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LangStoryRoute = LangStoryRouteImport.update({
  id: '/$lang/story',
  path: '/$lang/story',
  getParentRoute: () => rootRouteImport,
} as any)
const LangStudioroomRoute = LangStudioroomRouteImport.update({
  id: '/$lang/studioroom',
  path: '/$lang/studioroom',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTechnicalCofounderAlternativeRoute =
  LangTechnicalCofounderAlternativeRouteImport.update({
    id: '/$lang/technical-cofounder-alternative',
    path: '/$lang/technical-cofounder-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangTermsOfServiceRoute = LangTermsOfServiceRouteImport.update({
  id: '/$lang/terms-of-service',
  path: '/$lang/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LangXportmatchRoute = LangXportmatchRouteImport.update({
  id: '/$lang/xportmatch',
  path: '/$lang/xportmatch',
  getParentRoute: () => rootRouteImport,
} as any)
const BizmeetIndexRoute = BizmeetIndexRouteImport.update({
  id: '/bizmeet/',
  path: '/bizmeet/',
  getParentRoute: () => rootRouteImport,
} as any)
const BizmeetDemoRoute = BizmeetDemoRouteImport.update({
  id: '/bizmeet/demo',
  path: '/bizmeet/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EsServiciosRoute = EsServiciosRouteImport.update({
  id: '/es/servicios',
  path: '/es/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const EsSocioComercialRoute = EsSocioComercialRouteImport.update({
  id: '/es/socio-comercial',
  path: '/es/socio-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PikpcashIndexRoute = PikpcashIndexRouteImport.update({
  id: '/pikpcash/',
  path: '/pikpcash/',
  getParentRoute: () => rootRouteImport,
} as any)
const PikpcashDataroomRoute = PikpcashDataroomRouteImport.update({
  id: '/pikpcash/dataroom',
  path: '/pikpcash/dataroom',
  getParentRoute: () => rootRouteImport,
} as any)
const PikpcashSystemRoute = PikpcashSystemRouteImport.update({
  id: '/pikpcash/system',
  path: '/pikpcash/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SvAnsokRoute = SvAnsokRouteImport.update({
  id: '/sv/ansok',
  path: '/sv/ansok',
  getParentRoute: () => rootRouteImport,
} as any)
const SvSaljpartnerRoute = SvSaljpartnerRouteImport.update({
  id: '/sv/saljpartner',
  path: '/sv/saljpartner',
  getParentRoute: () => rootRouteImport,
} as any)
const SvTjansterRoute = SvTjansterRouteImport.update({
  id: '/sv/tjanster',
  path: '/sv/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBizmeetIndexRoute = LangBizmeetIndexRouteImport.update({
  id: '/$lang/bizmeet/',
  path: '/$lang/bizmeet/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBizmeetDemoRoute = LangBizmeetDemoRouteImport.update({
  id: '/$lang/bizmeet/demo',
  path: '/$lang/bizmeet/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGyrocraftIndexRoute = LangGyrocraftIndexRouteImport.update({
  id: '/$lang/gyrocraft/',
  path: '/$lang/gyrocraft/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGyrocraftAboutRoute = LangGyrocraftAboutRouteImport.update({
  id: '/$lang/gyrocraft/about',
  path: '/$lang/gyrocraft/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGyrocraftAcquisitionRoute =
  LangGyrocraftAcquisitionRouteImport.update({
    id: '/$lang/gyrocraft/acquisition',
    path: '/$lang/gyrocraft/acquisition',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangGyrocraftInvestorsRoute = LangGyrocraftInvestorsRouteImport.update({
  id: '/$lang/gyrocraft/investors',
  path: '/$lang/gyrocraft/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGyrocraftLicensingRoute = LangGyrocraftLicensingRouteImport.update({
  id: '/$lang/gyrocraft/licensing',
  path: '/$lang/gyrocraft/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const LangJournalIndexRoute = LangJournalIndexRouteImport.update({
  id: '/$lang/journal/',
  path: '/$lang/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangJournalSlugRoute = LangJournalSlugRouteImport.update({
  id: '/$lang/journal/$slug',
  path: '/$lang/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPikpcashIndexRoute = LangPikpcashIndexRouteImport.update({
  id: '/$lang/pikpcash/',
  path: '/$lang/pikpcash/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPikpcashDataroomRoute = LangPikpcashDataroomRouteImport.update({
  id: '/$lang/pikpcash/dataroom',
  path: '/$lang/pikpcash/dataroom',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPikpcashSystemRoute = LangPikpcashSystemRouteImport.update({
  id: '/$lang/pikpcash/system',
  path: '/$lang/pikpcash/system',
  getParentRoute: () => rootRouteImport,
} as any)
const LangVenturesPratisRoute = LangVenturesPratisRouteImport.update({
  id: '/$lang/ventures/pratis',
  path: '/$lang/ventures/pratis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarmsole': typeof AlarmsoleRoute
  '/beredskapad': typeof BeredskapadRoute
  '/eaktiebok-draknaste': typeof EaktiebokDraknasteRoute
  '/evidence': typeof EvidenceRoute
  '/hundelser': typeof HundelserRoute
  '/metadatamachine': typeof MetadatamachineRoute
  '/partner': typeof PartnerRoute
  '/partysta': typeof PartystaRoute
  '/pratis': typeof PratisRoute
  '/story': typeof StoryRoute
  '/studioroom': typeof StudioroomRoute
  '/xportmatch': typeof XportmatchRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/alarmsole': typeof LangAlarmsoleRoute
  '/$lang/angel-investor': typeof LangAngelInvestorRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/apply-for-investment': typeof LangApplyForInvestmentRoute
  '/$lang/beredskapad': typeof LangBeredskapadRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/brief': typeof LangBriefRoute
  '/$lang/build-for-equity': typeof LangBuildForEquityRoute
  '/$lang/configure': typeof LangConfigureRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/eaktiebok-draknaste': typeof LangEaktiebokDraknasteRoute
  '/$lang/evidence': typeof LangEvidenceRoute
  '/$lang/hundelser': typeof LangHundelserRoute
  '/$lang/invest': typeof LangInvestRoute
  '/$lang/metadatamachine': typeof LangMetadatamachineRoute
  '/$lang/partner': typeof LangPartnerRoute
  '/$lang/partysta': typeof LangPartystaRoute
  '/$lang/patent-strategy-for-startups': typeof LangPatentStrategyForStartupsRoute
  '/$lang/portfolio': typeof LangPortfolioRoute
  '/$lang/pratis': typeof LangPratisRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/sales-partner': typeof LangSalesPartnerRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/story': typeof LangStoryRoute
  '/$lang/studioroom': typeof LangStudioroomRoute
  '/$lang/technical-cofounder-alternative': typeof LangTechnicalCofounderAlternativeRoute
  '/$lang/terms-of-service': typeof LangTermsOfServiceRoute
  '/$lang/xportmatch': typeof LangXportmatchRoute
  '/bizmeet/demo': typeof BizmeetDemoRoute
  '/es/servicios': typeof EsServiciosRoute
  '/es/socio-comercial': typeof EsSocioComercialRoute
  '/pikpcash/dataroom': typeof PikpcashDataroomRoute
  '/pikpcash/system': typeof PikpcashSystemRoute
  '/sv/ansok': typeof SvAnsokRoute
  '/sv/saljpartner': typeof SvSaljpartnerRoute
  '/sv/tjanster': typeof SvTjansterRoute
  '/$lang/': typeof LangIndexRoute
  '/bizmeet/': typeof BizmeetIndexRoute
  '/pikpcash/': typeof PikpcashIndexRoute
  '/$lang/bizmeet/demo': typeof LangBizmeetDemoRoute
  '/$lang/gyrocraft/about': typeof LangGyrocraftAboutRoute
  '/$lang/gyrocraft/acquisition': typeof LangGyrocraftAcquisitionRoute
  '/$lang/gyrocraft/investors': typeof LangGyrocraftInvestorsRoute
  '/$lang/gyrocraft/licensing': typeof LangGyrocraftLicensingRoute
  '/$lang/journal/$slug': typeof LangJournalSlugRoute
  '/$lang/pikpcash/dataroom': typeof LangPikpcashDataroomRoute
  '/$lang/pikpcash/system': typeof LangPikpcashSystemRoute
  '/$lang/ventures/pratis': typeof LangVenturesPratisRoute
  '/$lang/bizmeet/': typeof LangBizmeetIndexRoute
  '/$lang/gyrocraft/': typeof LangGyrocraftIndexRoute
  '/$lang/journal/': typeof LangJournalIndexRoute
  '/$lang/pikpcash/': typeof LangPikpcashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarmsole': typeof AlarmsoleRoute
  '/beredskapad': typeof BeredskapadRoute
  '/eaktiebok-draknaste': typeof EaktiebokDraknasteRoute
  '/evidence': typeof EvidenceRoute
  '/hundelser': typeof HundelserRoute
  '/metadatamachine': typeof MetadatamachineRoute
  '/partner': typeof PartnerRoute
  '/partysta': typeof PartystaRoute
  '/pratis': typeof PratisRoute
  '/story': typeof StoryRoute
  '/studioroom': typeof StudioroomRoute
  '/xportmatch': typeof XportmatchRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/alarmsole': typeof LangAlarmsoleRoute
  '/$lang/angel-investor': typeof LangAngelInvestorRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/apply-for-investment': typeof LangApplyForInvestmentRoute
  '/$lang/beredskapad': typeof LangBeredskapadRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/brief': typeof LangBriefRoute
  '/$lang/build-for-equity': typeof LangBuildForEquityRoute
  '/$lang/configure': typeof LangConfigureRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/eaktiebok-draknaste': typeof LangEaktiebokDraknasteRoute
  '/$lang/evidence': typeof LangEvidenceRoute
  '/$lang/hundelser': typeof LangHundelserRoute
  '/$lang/invest': typeof LangInvestRoute
  '/$lang/metadatamachine': typeof LangMetadatamachineRoute
  '/$lang/partner': typeof LangPartnerRoute
  '/$lang/partysta': typeof LangPartystaRoute
  '/$lang/patent-strategy-for-startups': typeof LangPatentStrategyForStartupsRoute
  '/$lang/portfolio': typeof LangPortfolioRoute
  '/$lang/pratis': typeof LangPratisRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/sales-partner': typeof LangSalesPartnerRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/story': typeof LangStoryRoute
  '/$lang/studioroom': typeof LangStudioroomRoute
  '/$lang/technical-cofounder-alternative': typeof LangTechnicalCofounderAlternativeRoute
  '/$lang/terms-of-service': typeof LangTermsOfServiceRoute
  '/$lang/xportmatch': typeof LangXportmatchRoute
  '/bizmeet/demo': typeof BizmeetDemoRoute
  '/es/servicios': typeof EsServiciosRoute
  '/es/socio-comercial': typeof EsSocioComercialRoute
  '/pikpcash/dataroom': typeof PikpcashDataroomRoute
  '/pikpcash/system': typeof PikpcashSystemRoute
  '/sv/ansok': typeof SvAnsokRoute
  '/sv/saljpartner': typeof SvSaljpartnerRoute
  '/sv/tjanster': typeof SvTjansterRoute
  '/$lang': typeof LangIndexRoute
  '/bizmeet': typeof BizmeetIndexRoute
  '/pikpcash': typeof PikpcashIndexRoute
  '/$lang/bizmeet/demo': typeof LangBizmeetDemoRoute
  '/$lang/gyrocraft/about': typeof LangGyrocraftAboutRoute
  '/$lang/gyrocraft/acquisition': typeof LangGyrocraftAcquisitionRoute
  '/$lang/gyrocraft/investors': typeof LangGyrocraftInvestorsRoute
  '/$lang/gyrocraft/licensing': typeof LangGyrocraftLicensingRoute
  '/$lang/journal/$slug': typeof LangJournalSlugRoute
  '/$lang/pikpcash/dataroom': typeof LangPikpcashDataroomRoute
  '/$lang/pikpcash/system': typeof LangPikpcashSystemRoute
  '/$lang/ventures/pratis': typeof LangVenturesPratisRoute
  '/$lang/bizmeet': typeof LangBizmeetIndexRoute
  '/$lang/gyrocraft': typeof LangGyrocraftIndexRoute
  '/$lang/journal': typeof LangJournalIndexRoute
  '/$lang/pikpcash': typeof LangPikpcashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarmsole': typeof AlarmsoleRoute
  '/beredskapad': typeof BeredskapadRoute
  '/eaktiebok-draknaste': typeof EaktiebokDraknasteRoute
  '/evidence': typeof EvidenceRoute
  '/hundelser': typeof HundelserRoute
  '/metadatamachine': typeof MetadatamachineRoute
  '/partner': typeof PartnerRoute
  '/partysta': typeof PartystaRoute
  '/pratis': typeof PratisRoute
  '/story': typeof StoryRoute
  '/studioroom': typeof StudioroomRoute
  '/xportmatch': typeof XportmatchRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/alarmsole': typeof LangAlarmsoleRoute
  '/$lang/angel-investor': typeof LangAngelInvestorRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/apply-for-investment': typeof LangApplyForInvestmentRoute
  '/$lang/beredskapad': typeof LangBeredskapadRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/brief': typeof LangBriefRoute
  '/$lang/build-for-equity': typeof LangBuildForEquityRoute
  '/$lang/configure': typeof LangConfigureRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/eaktiebok-draknaste': typeof LangEaktiebokDraknasteRoute
  '/$lang/evidence': typeof LangEvidenceRoute
  '/$lang/hundelser': typeof LangHundelserRoute
  '/$lang/invest': typeof LangInvestRoute
  '/$lang/metadatamachine': typeof LangMetadatamachineRoute
  '/$lang/partner': typeof LangPartnerRoute
  '/$lang/partysta': typeof LangPartystaRoute
  '/$lang/patent-strategy-for-startups': typeof LangPatentStrategyForStartupsRoute
  '/$lang/portfolio': typeof LangPortfolioRoute
  '/$lang/pratis': typeof LangPratisRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/sales-partner': typeof LangSalesPartnerRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/story': typeof LangStoryRoute
  '/$lang/studioroom': typeof LangStudioroomRoute
  '/$lang/technical-cofounder-alternative': typeof LangTechnicalCofounderAlternativeRoute
  '/$lang/terms-of-service': typeof LangTermsOfServiceRoute
  '/$lang/xportmatch': typeof LangXportmatchRoute
  '/bizmeet/demo': typeof BizmeetDemoRoute
  '/es/servicios': typeof EsServiciosRoute
  '/es/socio-comercial': typeof EsSocioComercialRoute
  '/pikpcash/dataroom': typeof PikpcashDataroomRoute
  '/pikpcash/system': typeof PikpcashSystemRoute
  '/sv/ansok': typeof SvAnsokRoute
  '/sv/saljpartner': typeof SvSaljpartnerRoute
  '/sv/tjanster': typeof SvTjansterRoute
  '/$lang/': typeof LangIndexRoute
  '/bizmeet/': typeof BizmeetIndexRoute
  '/pikpcash/': typeof PikpcashIndexRoute
  '/$lang/bizmeet/demo': typeof LangBizmeetDemoRoute
  '/$lang/gyrocraft/about': typeof LangGyrocraftAboutRoute
  '/$lang/gyrocraft/acquisition': typeof LangGyrocraftAcquisitionRoute
  '/$lang/gyrocraft/investors': typeof LangGyrocraftInvestorsRoute
  '/$lang/gyrocraft/licensing': typeof LangGyrocraftLicensingRoute
  '/$lang/journal/$slug': typeof LangJournalSlugRoute
  '/$lang/pikpcash/dataroom': typeof LangPikpcashDataroomRoute
  '/$lang/pikpcash/system': typeof LangPikpcashSystemRoute
  '/$lang/ventures/pratis': typeof LangVenturesPratisRoute
  '/$lang/bizmeet/': typeof LangBizmeetIndexRoute
  '/$lang/gyrocraft/': typeof LangGyrocraftIndexRoute
  '/$lang/journal/': typeof LangJournalIndexRoute
  '/$lang/pikpcash/': typeof LangPikpcashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarmsole'
    | '/beredskapad'
    | '/eaktiebok-draknaste'
    | '/evidence'
    | '/hundelser'
    | '/metadatamachine'
    | '/partner'
    | '/partysta'
    | '/pratis'
    | '/story'
    | '/studioroom'
    | '/xportmatch'
    | '/$lang/about'
    | '/$lang/alarmsole'
    | '/$lang/angel-investor'
    | '/$lang/apply'
    | '/$lang/apply-for-investment'
    | '/$lang/beredskapad'
    | '/$lang/blog'
    | '/$lang/brief'
    | '/$lang/build-for-equity'
    | '/$lang/configure'
    | '/$lang/contact'
    | '/$lang/eaktiebok-draknaste'
    | '/$lang/evidence'
    | '/$lang/hundelser'
    | '/$lang/invest'
    | '/$lang/metadatamachine'
    | '/$lang/partner'
    | '/$lang/partysta'
    | '/$lang/patent-strategy-for-startups'
    | '/$lang/portfolio'
    | '/$lang/pratis'
    | '/$lang/privacy-policy'
    | '/$lang/sales-partner'
    | '/$lang/services'
    | '/$lang/story'
    | '/$lang/studioroom'
    | '/$lang/technical-cofounder-alternative'
    | '/$lang/terms-of-service'
    | '/$lang/xportmatch'
    | '/bizmeet/demo'
    | '/es/servicios'
    | '/es/socio-comercial'
    | '/pikpcash/dataroom'
    | '/pikpcash/system'
    | '/sv/ansok'
    | '/sv/saljpartner'
    | '/sv/tjanster'
    | '/$lang/'
    | '/bizmeet/'
    | '/pikpcash/'
    | '/$lang/bizmeet/demo'
    | '/$lang/gyrocraft/about'
    | '/$lang/gyrocraft/acquisition'
    | '/$lang/gyrocraft/investors'
    | '/$lang/gyrocraft/licensing'
    | '/$lang/journal/$slug'
    | '/$lang/pikpcash/dataroom'
    | '/$lang/pikpcash/system'
    | '/$lang/ventures/pratis'
    | '/$lang/bizmeet/'
    | '/$lang/gyrocraft/'
    | '/$lang/journal/'
    | '/$lang/pikpcash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarmsole'
    | '/beredskapad'
    | '/eaktiebok-draknaste'
    | '/evidence'
    | '/hundelser'
    | '/metadatamachine'
    | '/partner'
    | '/partysta'
    | '/pratis'
    | '/story'
    | '/studioroom'
    | '/xportmatch'
    | '/$lang/about'
    | '/$lang/alarmsole'
    | '/$lang/angel-investor'
    | '/$lang/apply'
    | '/$lang/apply-for-investment'
    | '/$lang/beredskapad'
    | '/$lang/blog'
    | '/$lang/brief'
    | '/$lang/build-for-equity'
    | '/$lang/configure'
    | '/$lang/contact'
    | '/$lang/eaktiebok-draknaste'
    | '/$lang/evidence'
    | '/$lang/hundelser'
    | '/$lang/invest'
    | '/$lang/metadatamachine'
    | '/$lang/partner'
    | '/$lang/partysta'
    | '/$lang/patent-strategy-for-startups'
    | '/$lang/portfolio'
    | '/$lang/pratis'
    | '/$lang/privacy-policy'
    | '/$lang/sales-partner'
    | '/$lang/services'
    | '/$lang/story'
    | '/$lang/studioroom'
    | '/$lang/technical-cofounder-alternative'
    | '/$lang/terms-of-service'
    | '/$lang/xportmatch'
    | '/bizmeet/demo'
    | '/es/servicios'
    | '/es/socio-comercial'
    | '/pikpcash/dataroom'
    | '/pikpcash/system'
    | '/sv/ansok'
    | '/sv/saljpartner'
    | '/sv/tjanster'
    | '/$lang'
    | '/bizmeet'
    | '/pikpcash'
    | '/$lang/bizmeet/demo'
    | '/$lang/gyrocraft/about'
    | '/$lang/gyrocraft/acquisition'
    | '/$lang/gyrocraft/investors'
    | '/$lang/gyrocraft/licensing'
    | '/$lang/journal/$slug'
    | '/$lang/pikpcash/dataroom'
    | '/$lang/pikpcash/system'
    | '/$lang/ventures/pratis'
    | '/$lang/bizmeet'
    | '/$lang/gyrocraft'
    | '/$lang/journal'
    | '/$lang/pikpcash'
  id:
    | '__root__'
    | '/'
    | '/alarmsole'
    | '/beredskapad'
    | '/eaktiebok-draknaste'
    | '/evidence'
    | '/hundelser'
    | '/metadatamachine'
    | '/partner'
    | '/partysta'
    | '/pratis'
    | '/story'
    | '/studioroom'
    | '/xportmatch'
    | '/$lang/about'
    | '/$lang/alarmsole'
    | '/$lang/angel-investor'
    | '/$lang/apply'
    | '/$lang/apply-for-investment'
    | '/$lang/beredskapad'
    | '/$lang/blog'
    | '/$lang/brief'
    | '/$lang/build-for-equity'
    | '/$lang/configure'
    | '/$lang/contact'
    | '/$lang/eaktiebok-draknaste'
    | '/$lang/evidence'
    | '/$lang/hundelser'
    | '/$lang/invest'
    | '/$lang/metadatamachine'
    | '/$lang/partner'
    | '/$lang/partysta'
    | '/$lang/patent-strategy-for-startups'
    | '/$lang/portfolio'
    | '/$lang/pratis'
    | '/$lang/privacy-policy'
    | '/$lang/sales-partner'
    | '/$lang/services'
    | '/$lang/story'
    | '/$lang/studioroom'
    | '/$lang/technical-cofounder-alternative'
    | '/$lang/terms-of-service'
    | '/$lang/xportmatch'
    | '/bizmeet/demo'
    | '/es/servicios'
    | '/es/socio-comercial'
    | '/pikpcash/dataroom'
    | '/pikpcash/system'
    | '/sv/ansok'
    | '/sv/saljpartner'
    | '/sv/tjanster'
    | '/$lang/'
    | '/bizmeet/'
    | '/pikpcash/'
    | '/$lang/bizmeet/demo'
    | '/$lang/gyrocraft/about'
    | '/$lang/gyrocraft/acquisition'
    | '/$lang/gyrocraft/investors'
    | '/$lang/gyrocraft/licensing'
    | '/$lang/journal/$slug'
    | '/$lang/pikpcash/dataroom'
    | '/$lang/pikpcash/system'
    | '/$lang/ventures/pratis'
    | '/$lang/bizmeet/'
    | '/$lang/gyrocraft/'
    | '/$lang/journal/'
    | '/$lang/pikpcash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsoleRoute: typeof AlarmsoleRoute
  BeredskapadRoute: typeof BeredskapadRoute
  EaktiebokDraknasteRoute: typeof EaktiebokDraknasteRoute
  EvidenceRoute: typeof EvidenceRoute
  HundelserRoute: typeof HundelserRoute
  MetadatamachineRoute: typeof MetadatamachineRoute
  PartnerRoute: typeof PartnerRoute
  PartystaRoute: typeof PartystaRoute
  PratisRoute: typeof PratisRoute
  StoryRoute: typeof StoryRoute
  StudioroomRoute: typeof StudioroomRoute
  XportmatchRoute: typeof XportmatchRoute
  LangAboutRoute: typeof LangAboutRoute
  LangAlarmsoleRoute: typeof LangAlarmsoleRoute
  LangAngelInvestorRoute: typeof LangAngelInvestorRoute
  LangApplyRoute: typeof LangApplyRoute
  LangApplyForInvestmentRoute: typeof LangApplyForInvestmentRoute
  LangBeredskapadRoute: typeof LangBeredskapadRoute
  LangBlogRoute: typeof LangBlogRoute
  LangBriefRoute: typeof LangBriefRoute
  LangBuildForEquityRoute: typeof LangBuildForEquityRoute
  LangConfigureRoute: typeof LangConfigureRoute
  LangContactRoute: typeof LangContactRoute
  LangEaktiebokDraknasteRoute: typeof LangEaktiebokDraknasteRoute
  LangEvidenceRoute: typeof LangEvidenceRoute
  LangHundelserRoute: typeof LangHundelserRoute
  LangInvestRoute: typeof LangInvestRoute
  LangMetadatamachineRoute: typeof LangMetadatamachineRoute
  LangPartnerRoute: typeof LangPartnerRoute
  LangPartystaRoute: typeof LangPartystaRoute
  LangPatentStrategyForStartupsRoute: typeof LangPatentStrategyForStartupsRoute
  LangPortfolioRoute: typeof LangPortfolioRoute
  LangPratisRoute: typeof LangPratisRoute
  LangPrivacyPolicyRoute: typeof LangPrivacyPolicyRoute
  LangSalesPartnerRoute: typeof LangSalesPartnerRoute
  LangServicesRoute: typeof LangServicesRoute
  LangStoryRoute: typeof LangStoryRoute
  LangStudioroomRoute: typeof LangStudioroomRoute
  LangTechnicalCofounderAlternativeRoute: typeof LangTechnicalCofounderAlternativeRoute
  LangTermsOfServiceRoute: typeof LangTermsOfServiceRoute
  LangXportmatchRoute: typeof LangXportmatchRoute
  BizmeetDemoRoute: typeof BizmeetDemoRoute
  EsServiciosRoute: typeof EsServiciosRoute
  EsSocioComercialRoute: typeof EsSocioComercialRoute
  PikpcashDataroomRoute: typeof PikpcashDataroomRoute
  PikpcashSystemRoute: typeof PikpcashSystemRoute
  SvAnsokRoute: typeof SvAnsokRoute
  SvSaljpartnerRoute: typeof SvSaljpartnerRoute
  SvTjansterRoute: typeof SvTjansterRoute
  LangIndexRoute: typeof LangIndexRoute
  BizmeetIndexRoute: typeof BizmeetIndexRoute
  PikpcashIndexRoute: typeof PikpcashIndexRoute
  LangBizmeetDemoRoute: typeof LangBizmeetDemoRoute
  LangGyrocraftAboutRoute: typeof LangGyrocraftAboutRoute
  LangGyrocraftAcquisitionRoute: typeof LangGyrocraftAcquisitionRoute
  LangGyrocraftInvestorsRoute: typeof LangGyrocraftInvestorsRoute
  LangGyrocraftLicensingRoute: typeof LangGyrocraftLicensingRoute
  LangJournalSlugRoute: typeof LangJournalSlugRoute
  LangPikpcashDataroomRoute: typeof LangPikpcashDataroomRoute
  LangPikpcashSystemRoute: typeof LangPikpcashSystemRoute
  LangVenturesPratisRoute: typeof LangVenturesPratisRoute
  LangBizmeetIndexRoute: typeof LangBizmeetIndexRoute
  LangGyrocraftIndexRoute: typeof LangGyrocraftIndexRoute
  LangJournalIndexRoute: typeof LangJournalIndexRoute
  LangPikpcashIndexRoute: typeof LangPikpcashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarmsole': {
      id: '/alarmsole'
      path: '/alarmsole'
      fullPath: '/alarmsole'
      preLoaderRoute: typeof AlarmsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beredskapad': {
      id: '/beredskapad'
      path: '/beredskapad'
      fullPath: '/beredskapad'
      preLoaderRoute: typeof BeredskapadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eaktiebok-draknaste': {
      id: '/eaktiebok-draknaste'
      path: '/eaktiebok-draknaste'
      fullPath: '/eaktiebok-draknaste'
      preLoaderRoute: typeof EaktiebokDraknasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundelser': {
      id: '/hundelser'
      path: '/hundelser'
      fullPath: '/hundelser'
      preLoaderRoute: typeof HundelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadatamachine': {
      id: '/metadatamachine'
      path: '/metadatamachine'
      fullPath: '/metadatamachine'
      preLoaderRoute: typeof MetadatamachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partysta': {
      id: '/partysta'
      path: '/partysta'
      fullPath: '/partysta'
      preLoaderRoute: typeof PartystaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratis': {
      id: '/pratis'
      path: '/pratis'
      fullPath: '/pratis'
      preLoaderRoute: typeof PratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studioroom': {
      id: '/studioroom'
      path: '/studioroom'
      fullPath: '/studioroom'
      preLoaderRoute: typeof StudioroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xportmatch': {
      id: '/xportmatch'
      path: '/xportmatch'
      fullPath: '/xportmatch'
      preLoaderRoute: typeof XportmatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/alarmsole': {
      id: '/$lang/alarmsole'
      path: '/$lang/alarmsole'
      fullPath: '/$lang/alarmsole'
      preLoaderRoute: typeof LangAlarmsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/angel-investor': {
      id: '/$lang/angel-investor'
      path: '/$lang/angel-investor'
      fullPath: '/$lang/angel-investor'
      preLoaderRoute: typeof LangAngelInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/apply': {
      id: '/$lang/apply'
      path: '/$lang/apply'
      fullPath: '/$lang/apply'
      preLoaderRoute: typeof LangApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/apply-for-investment': {
      id: '/$lang/apply-for-investment'
      path: '/$lang/apply-for-investment'
      fullPath: '/$lang/apply-for-investment'
      preLoaderRoute: typeof LangApplyForInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/beredskapad': {
      id: '/$lang/beredskapad'
      path: '/$lang/beredskapad'
      fullPath: '/$lang/beredskapad'
      preLoaderRoute: typeof LangBeredskapadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/blog': {
      id: '/$lang/blog'
      path: '/$lang/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof LangBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/brief': {
      id: '/$lang/brief'
      path: '/$lang/brief'
      fullPath: '/$lang/brief'
      preLoaderRoute: typeof LangBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/build-for-equity': {
      id: '/$lang/build-for-equity'
      path: '/$lang/build-for-equity'
      fullPath: '/$lang/build-for-equity'
      preLoaderRoute: typeof LangBuildForEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/configure': {
      id: '/$lang/configure'
      path: '/$lang/configure'
      fullPath: '/$lang/configure'
      preLoaderRoute: typeof LangConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/$lang/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/eaktiebok-draknaste': {
      id: '/$lang/eaktiebok-draknaste'
      path: '/$lang/eaktiebok-draknaste'
      fullPath: '/$lang/eaktiebok-draknaste'
      preLoaderRoute: typeof LangEaktiebokDraknasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/evidence': {
      id: '/$lang/evidence'
      path: '/$lang/evidence'
      fullPath: '/$lang/evidence'
      preLoaderRoute: typeof LangEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/hundelser': {
      id: '/$lang/hundelser'
      path: '/$lang/hundelser'
      fullPath: '/$lang/hundelser'
      preLoaderRoute: typeof LangHundelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/invest': {
      id: '/$lang/invest'
      path: '/$lang/invest'
      fullPath: '/$lang/invest'
      preLoaderRoute: typeof LangInvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/metadatamachine': {
      id: '/$lang/metadatamachine'
      path: '/$lang/metadatamachine'
      fullPath: '/$lang/metadatamachine'
      preLoaderRoute: typeof LangMetadatamachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/partner': {
      id: '/$lang/partner'
      path: '/$lang/partner'
      fullPath: '/$lang/partner'
      preLoaderRoute: typeof LangPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/partysta': {
      id: '/$lang/partysta'
      path: '/$lang/partysta'
      fullPath: '/$lang/partysta'
      preLoaderRoute: typeof LangPartystaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/patent-strategy-for-startups': {
      id: '/$lang/patent-strategy-for-startups'
      path: '/$lang/patent-strategy-for-startups'
      fullPath: '/$lang/patent-strategy-for-startups'
      preLoaderRoute: typeof LangPatentStrategyForStartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/portfolio': {
      id: '/$lang/portfolio'
      path: '/$lang/portfolio'
      fullPath: '/$lang/portfolio'
      preLoaderRoute: typeof LangPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pratis': {
      id: '/$lang/pratis'
      path: '/$lang/pratis'
      fullPath: '/$lang/pratis'
      preLoaderRoute: typeof LangPratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/privacy-policy': {
      id: '/$lang/privacy-policy'
      path: '/$lang/privacy-policy'
      fullPath: '/$lang/privacy-policy'
      preLoaderRoute: typeof LangPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/sales-partner': {
      id: '/$lang/sales-partner'
      path: '/$lang/sales-partner'
      fullPath: '/$lang/sales-partner'
      preLoaderRoute: typeof LangSalesPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/$lang/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/story': {
      id: '/$lang/story'
      path: '/$lang/story'
      fullPath: '/$lang/story'
      preLoaderRoute: typeof LangStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/studioroom': {
      id: '/$lang/studioroom'
      path: '/$lang/studioroom'
      fullPath: '/$lang/studioroom'
      preLoaderRoute: typeof LangStudioroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/technical-cofounder-alternative': {
      id: '/$lang/technical-cofounder-alternative'
      path: '/$lang/technical-cofounder-alternative'
      fullPath: '/$lang/technical-cofounder-alternative'
      preLoaderRoute: typeof LangTechnicalCofounderAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/terms-of-service': {
      id: '/$lang/terms-of-service'
      path: '/$lang/terms-of-service'
      fullPath: '/$lang/terms-of-service'
      preLoaderRoute: typeof LangTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/xportmatch': {
      id: '/$lang/xportmatch'
      path: '/$lang/xportmatch'
      fullPath: '/$lang/xportmatch'
      preLoaderRoute: typeof LangXportmatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bizmeet/': {
      id: '/bizmeet/'
      path: '/bizmeet'
      fullPath: '/bizmeet/'
      preLoaderRoute: typeof BizmeetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bizmeet/demo': {
      id: '/bizmeet/demo'
      path: '/bizmeet/demo'
      fullPath: '/bizmeet/demo'
      preLoaderRoute: typeof BizmeetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/servicios': {
      id: '/es/servicios'
      path: '/es/servicios'
      fullPath: '/es/servicios'
      preLoaderRoute: typeof EsServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/socio-comercial': {
      id: '/es/socio-comercial'
      path: '/es/socio-comercial'
      fullPath: '/es/socio-comercial'
      preLoaderRoute: typeof EsSocioComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pikpcash/': {
      id: '/pikpcash/'
      path: '/pikpcash'
      fullPath: '/pikpcash/'
      preLoaderRoute: typeof PikpcashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pikpcash/dataroom': {
      id: '/pikpcash/dataroom'
      path: '/pikpcash/dataroom'
      fullPath: '/pikpcash/dataroom'
      preLoaderRoute: typeof PikpcashDataroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pikpcash/system': {
      id: '/pikpcash/system'
      path: '/pikpcash/system'
      fullPath: '/pikpcash/system'
      preLoaderRoute: typeof PikpcashSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv/ansok': {
      id: '/sv/ansok'
      path: '/sv/ansok'
      fullPath: '/sv/ansok'
      preLoaderRoute: typeof SvAnsokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv/saljpartner': {
      id: '/sv/saljpartner'
      path: '/sv/saljpartner'
      fullPath: '/sv/saljpartner'
      preLoaderRoute: typeof SvSaljpartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv/tjanster': {
      id: '/sv/tjanster'
      path: '/sv/tjanster'
      fullPath: '/sv/tjanster'
      preLoaderRoute: typeof SvTjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/bizmeet/': {
      id: '/$lang/bizmeet/'
      path: '/$lang/bizmeet'
      fullPath: '/$lang/bizmeet/'
      preLoaderRoute: typeof LangBizmeetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/bizmeet/demo': {
      id: '/$lang/bizmeet/demo'
      path: '/$lang/bizmeet/demo'
      fullPath: '/$lang/bizmeet/demo'
      preLoaderRoute: typeof LangBizmeetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gyrocraft/': {
      id: '/$lang/gyrocraft/'
      path: '/$lang/gyrocraft'
      fullPath: '/$lang/gyrocraft/'
      preLoaderRoute: typeof LangGyrocraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gyrocraft/about': {
      id: '/$lang/gyrocraft/about'
      path: '/$lang/gyrocraft/about'
      fullPath: '/$lang/gyrocraft/about'
      preLoaderRoute: typeof LangGyrocraftAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gyrocraft/acquisition': {
      id: '/$lang/gyrocraft/acquisition'
      path: '/$lang/gyrocraft/acquisition'
      fullPath: '/$lang/gyrocraft/acquisition'
      preLoaderRoute: typeof LangGyrocraftAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gyrocraft/investors': {
      id: '/$lang/gyrocraft/investors'
      path: '/$lang/gyrocraft/investors'
      fullPath: '/$lang/gyrocraft/investors'
      preLoaderRoute: typeof LangGyrocraftInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gyrocraft/licensing': {
      id: '/$lang/gyrocraft/licensing'
      path: '/$lang/gyrocraft/licensing'
      fullPath: '/$lang/gyrocraft/licensing'
      preLoaderRoute: typeof LangGyrocraftLicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/journal/': {
      id: '/$lang/journal/'
      path: '/$lang/journal'
      fullPath: '/$lang/journal/'
      preLoaderRoute: typeof LangJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/journal/$slug': {
      id: '/$lang/journal/$slug'
      path: '/$lang/journal/$slug'
      fullPath: '/$lang/journal/$slug'
      preLoaderRoute: typeof LangJournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pikpcash/': {
      id: '/$lang/pikpcash/'
      path: '/$lang/pikpcash'
      fullPath: '/$lang/pikpcash/'
      preLoaderRoute: typeof LangPikpcashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pikpcash/dataroom': {
      id: '/$lang/pikpcash/dataroom'
      path: '/$lang/pikpcash/dataroom'
      fullPath: '/$lang/pikpcash/dataroom'
      preLoaderRoute: typeof LangPikpcashDataroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pikpcash/system': {
      id: '/$lang/pikpcash/system'
      path: '/$lang/pikpcash/system'
      fullPath: '/$lang/pikpcash/system'
      preLoaderRoute: typeof LangPikpcashSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/ventures/pratis': {
      id: '/$lang/ventures/pratis'
      path: '/$lang/ventures/pratis'
      fullPath: '/$lang/ventures/pratis'
      preLoaderRoute: typeof LangVenturesPratisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsoleRoute: AlarmsoleRoute,
  BeredskapadRoute: BeredskapadRoute,
  EaktiebokDraknasteRoute: EaktiebokDraknasteRoute,
  EvidenceRoute: EvidenceRoute,
  HundelserRoute: HundelserRoute,
  MetadatamachineRoute: MetadatamachineRoute,
  PartnerRoute: PartnerRoute,
  PartystaRoute: PartystaRoute,
  PratisRoute: PratisRoute,
  StoryRoute: StoryRoute,
  StudioroomRoute: StudioroomRoute,
  XportmatchRoute: XportmatchRoute,
  LangAboutRoute: LangAboutRoute,
  LangAlarmsoleRoute: LangAlarmsoleRoute,
  LangAngelInvestorRoute: LangAngelInvestorRoute,
  LangApplyRoute: LangApplyRoute,
  LangApplyForInvestmentRoute: LangApplyForInvestmentRoute,
  LangBeredskapadRoute: LangBeredskapadRoute,
  LangBlogRoute: LangBlogRoute,
  LangBriefRoute: LangBriefRoute,
  LangBuildForEquityRoute: LangBuildForEquityRoute,
  LangConfigureRoute: LangConfigureRoute,
  LangContactRoute: LangContactRoute,
  LangEaktiebokDraknasteRoute: LangEaktiebokDraknasteRoute,
  LangEvidenceRoute: LangEvidenceRoute,
  LangHundelserRoute: LangHundelserRoute,
  LangInvestRoute: LangInvestRoute,
  LangMetadatamachineRoute: LangMetadatamachineRoute,
  LangPartnerRoute: LangPartnerRoute,
  LangPartystaRoute: LangPartystaRoute,
  LangPatentStrategyForStartupsRoute: LangPatentStrategyForStartupsRoute,
  LangPortfolioRoute: LangPortfolioRoute,
  LangPratisRoute: LangPratisRoute,
  LangPrivacyPolicyRoute: LangPrivacyPolicyRoute,
  LangSalesPartnerRoute: LangSalesPartnerRoute,
  LangServicesRoute: LangServicesRoute,
  LangStoryRoute: LangStoryRoute,
  LangStudioroomRoute: LangStudioroomRoute,
  LangTechnicalCofounderAlternativeRoute:
    LangTechnicalCofounderAlternativeRoute,
  LangTermsOfServiceRoute: LangTermsOfServiceRoute,
  LangXportmatchRoute: LangXportmatchRoute,
  BizmeetDemoRoute: BizmeetDemoRoute,
  EsServiciosRoute: EsServiciosRoute,
  EsSocioComercialRoute: EsSocioComercialRoute,
  PikpcashDataroomRoute: PikpcashDataroomRoute,
  PikpcashSystemRoute: PikpcashSystemRoute,
  SvAnsokRoute: SvAnsokRoute,
  SvSaljpartnerRoute: SvSaljpartnerRoute,
  SvTjansterRoute: SvTjansterRoute,
  LangIndexRoute: LangIndexRoute,
  BizmeetIndexRoute: BizmeetIndexRoute,
  PikpcashIndexRoute: PikpcashIndexRoute,
  LangBizmeetDemoRoute: LangBizmeetDemoRoute,
  LangGyrocraftAboutRoute: LangGyrocraftAboutRoute,
  LangGyrocraftAcquisitionRoute: LangGyrocraftAcquisitionRoute,
  LangGyrocraftInvestorsRoute: LangGyrocraftInvestorsRoute,
  LangGyrocraftLicensingRoute: LangGyrocraftLicensingRoute,
  LangJournalSlugRoute: LangJournalSlugRoute,
  LangPikpcashDataroomRoute: LangPikpcashDataroomRoute,
  LangPikpcashSystemRoute: LangPikpcashSystemRoute,
  LangVenturesPratisRoute: LangVenturesPratisRoute,
  LangBizmeetIndexRoute: LangBizmeetIndexRoute,
  LangGyrocraftIndexRoute: LangGyrocraftIndexRoute,
  LangJournalIndexRoute: LangJournalIndexRoute,
  LangPikpcashIndexRoute: LangPikpcashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
